# Site settings
title: 代码与音乐
email: qbcs@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just for fun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://祁冰.cn" # the base hostname & protocol for your site
weibo_username: hustqibing
weibo_nickname: 大冰qbcs
#twitter_username: bingful
github_username: qbcs

# Build settings
markdown: kramdown

timezone: Asia/Shanghai

permalink: /:categories/:title 
